"""Generate per-unit VapourSynth scripts from job.toml.

Output 0 is the encode input (10-bit), output 1 is the untouched source for
comparisons. Scripts import videocook, so vspipe must run inside the uv venv.
"""

from __future__ import annotations

import runpy
from pathlib import Path

import vapoursynth as vs

from videocook.job import Job, deep_merge

TEMPLATE = '''\
# Generated by `vcook script` for job {job!r}, unit {unit!r}.
# Edit job.toml and regenerate; or edit this file and set video.script_locked = true.
import vapoursynth as vs
from videocook import filters as F
from videocook.vsource import open_source

core = vs.core

SOURCE = {source}
CACHE = r"{cache}"
TRIM = {trim}          # [[first, last_exclusive], ...] for --trim test runs
FILTERS = {filters}
ZONES = {zones}        # [{{"range": [a, b], "filters": {{...}}}}] overrides per frame range

src = open_source(SOURCE, CACHE)
if TRIM:
    src = core.std.Splice([src[a:b] for a, b in TRIM])


def chain(clip, cfg):
    if not any(cfg.get(k) for k in ("denoise", "deband", "aa", "field")):
        clip = F.crop(clip, **cfg["crop"]) if cfg.get("crop") else clip
        return clip if clip.format.bits_per_sample == 10 else F.to10(clip)
    return F.to10(F.standard_chain(clip, cfg))


res = chain(src, FILTERS)
for zone in ZONES:
    a, b = zone["range"]
    alt = chain(src, {{**FILTERS, **zone["filters"]}})
    parts = ([res[:a]] if a > 0 else []) + [alt[a:b]] + ([res[b:]] if b < res.num_frames else [])
    res = core.std.Splice(parts)

res.set_output(0)
src.set_output(1)
'''


def unit_config(job: Job, unit: dict) -> tuple[dict, list]:
    filters = deep_merge(job.data["video"].get("filters", {}), unit.get("filters", {}))
    return filters, unit.get("zones", [])


def script_path(job: Job, unit_id: str) -> Path:
    return job.sub("scripts") / f"{unit_id}.vpy"


def generate(job: Job) -> list[Path]:
    paths = []
    for unit in job.units():
        path = script_path(job, unit["id"])
        if job.data["video"].get("script_locked") and path.exists():
            paths.append(path)
            continue
        filters, zones = unit_config(job, unit)
        path.write_text(TEMPLATE.format(
            job=job.data["job"]["name"], unit=unit["id"],
            source=repr(unit["source"]),
            cache=str(job.cache), trim=repr(job.data["run"].get("trim") or []),
            filters=repr(filters), zones=repr(zones)), encoding="utf-8")
        paths.append(path)
    return paths


def load_outputs(path: Path) -> tuple[vs.VideoNode, vs.VideoNode]:
    """Evaluate a generated script in-process and return (result, source)."""
    vs.clear_outputs()
    runpy.run_path(str(path))
    res = vs.get_output(0)
    src = vs.get_output(1)
    res = res.clip if hasattr(res, "clip") else res
    src = src.clip if hasattr(src, "clip") else src
    return res, src
